export const PATH_NAVIGATION_DEMO= 'navigation'
export const PATH_NAVIGATION_LIST = 'navigation_list'
export const PATH_NAVIGATION_HOME = 'navigation_home'
export const PATH_NAVIGATION_HOME_HOOK = 'navigation_home_hook'
export const PATH_NAVIGATION_COMPACT = 'navigation_compact'
export const PATH_NAVIGATION_DETAIL = 'navigation_detail'
export const PATH_NAVIGATION_CONFIG_DEFAULT_HEADER_BAR_STYLE = 'navigation_header_bar'
export const PATH_NAVIGATION_CUSTOM_HEADER_BAR_TITLE = 'navigation_custom_header_bar_title'
export const PATH_NAVIGATION_CUSTOM_HEADER_BAR = 'navigation_custom_header_bar'
export const PATH_NAVIGATION_LIFE_CYCLE = 'navigation_life_cycle'
export const PATH_FULL_SCREEN_MODAL = 'navigation_open_full_screen_modal'
export const PATH_AUTHENTICATION = 'navigation_authentication'
export const PATH_AUTHENTICATION_SIGN_IN = 'navigation_authentication_signin'
export const PATH_AUTHENTICATION_SETTING = 'navigation_authentication_setting'
export const PATH_NAVIGATION_STATUSBAR1 = 'navigation_navigation_statusbar1'
export const PATH_NAVIGATION_STATUSBAR2 = 'navigation_navigation_statusbar2'
export const PATH_NAVIGATION_CUSTOM_BACK_BUTTON_BEHAVIOR = 'navigation_custom_back_button_navigator'
export const PATH_NAVIGATION_PREVENT_GOBACK = 'navigation_prevent_goback'
export const PATH_ACCESS_NAVIGATION_PROPS = 'navigation_access_props'


