export const PATH_HOME = "home"; //首页
export const PATH_ACTIVITY_INDICATOR = "indicator"; //loading 页面
export const PATH_BUTTON = "Button"; //Button 页面
export const PATH_FLAT_LIST = "FlatList"; //FlatList 页面
export const PATH_IMAGE = "Image"; //Image 页面
export const PATH_IMAGE_BACKGROUND = "ImageBackground"; //ImageBackground 页面
export const PATH_KEYBOARD = "KeyBoardAvoidingView"; //ImageBackground 页面
export const PATH_MODAL = "Modal"; //Modal 页面
export const PATH_PRESSABLE = "Pressable"; //Pressable 页面
export const PATH_REFRESH_CONTROL = "RefreshControl"; //RefreshControl 页面
export const PATH_SCROLLVIEW = "ScrollView"; //ScrollView 页面
export const PATH_SECTION_LIST = "SectionList"; //SectionList 页面
export const PATH_STATUSBAR = "StatusBar"; //StatusBar 页面
export const PATH_SWITCH = "Switch"; //Switch 页面
export const PATH_TEXT = "Text"; //Text
export const PATH_TEXT_INPUT = "TextInput"; //TextInput
export const PATH_TOUCHABLE_HIGHLIGHT = "TouchableHighlight"; //TouchableHighlight
export const PATH_TOUCHABLE_OPACITY = "TouchableOpacity"; //TouchableOpacity
export const PATH_FLEX_VERIFY_PWD = "Flex"; //Flex
export const PATH_FLEX_GRAMMAR = "FlexGrammar"; //FlexGrammar
export const PATH_FLEX_ALIGN_CONTENT_SELF = "FlexAlignContentSelf"; //FlexGrow
export const PATH_FLEX_DICE = "FlexDice"; //FlexDice
export const PATH_FC_TODO = "FcTodo"; //函数式组件
